# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e361e591739cdabe2a8fa2967a5adf693ab2b893e6a93222ce8552eb96c1ccce40cdb878f2e6f9b22904e6e528d6477b3ab9f7d677fc51a05370a091f080d72

test:
  secret_key_base: 0109ae760ee209b156b46a61a9095a76b1f2e258eca6989d4b683a7e412c1ad6637f1540b83819d106fbfd6dcbee82d3f56b7fe6ce05c6e21383b2b892b938a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
